name: linea_de_vida
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  timeline_tile: ^2.0.0
  flutter_animate: ^4.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- PAQUETE PARA EL VIDEO AÑADIDO ---
  video_player: ^2.8.1
  
  file_picker: ^10.3.10
  record: ^6.2.0
  js: ^0.7.2
  provider: ^6.0.5
  path_provider: ^2.0.11
  http: ^1.6.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true